export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const LOGIN_ALERT = 'LOGIN_ALERT';

export const TOGGLE_IS_MEMBER = 'TOGGLE_IS_MEMBER';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_FAIL = 'SETUP_USER_FAIL';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_CALORIE_BEGIN = 'GET_CALORIE_BEGIN';
export const GET_CALORIE_SUCCESS = 'GET_CALORIE_SUCCESS';
export const GET_CALORIE_FAIL = 'GET_CALORIE_FAIL';

export const CALCULATE_CALORIE_SUCCESS = 'CALCULATE_CALORIE_SUCCESS';
export const CALCULATE_CALORIE_FAIL = 'CALCULATE_CALORIE_FAIL';
